export const initialCampaignMetadata: Record<string, any> = {
  "WBF964": {"campaignId":964,"customName":"Win-Back Lapsed Customers","label":"Win-Back","description":"Re-engagement flow for customers who have churned. Attempts to bring them back with targeted messaging.","metrics":{"volume":"1,079","openRate":"48.7%","clickRate":"0.0%"}},
  "LUF916": {"campaignId":916,"customName":"Launch → Upgrade Nudge","label":"Main Flow","description":"Long-running sequence nudging Launch plan customers to upgrade to Plus or Growth.","metrics":{"volume":"22,605","openRate":"39.6%","clickRate":"0.5%"}},
  "PLG1008": {"campaignId":1008,"customName":"Plus → Growth AM Emails","label":"Upgrade Pitch","description":"Targeted emails encouraging Plus customers to upgrade to the Growth plan.","metrics":{"volume":"808","openRate":"39.8%","clickRate":"4.1%"}},
  "UPGRADE918": {"campaignId":918,"customName":"Plus Upgrade Full Flow","label":"Main Flow","description":"Full nurture sequence encouraging Plus customers to upgrade, with multi-step touchpoints.","metrics":{"volume":"24,044","openRate":"40.0%","clickRate":"0.5%"}},
  "MTA250": {"campaignId":250,"customName":"Monthly → Annual Switch","label":"Billing Upsell","description":"Encourages monthly subscribers to switch to an annual billing plan. Focused on LTV extension.","metrics":{"volume":"47,398","openRate":"35.2%","clickRate":"1.4%"}},
  "PRF974": {"campaignId":974,"customName":"Plus Retention Main Flow","label":"Main Flow","description":"Core retention sequence for Plus plan customers. Drives full platform activation across all key features.","metrics":{"volume":"6,286","openRate":"38.2%","clickRate":"2.8%"}},
  "PDO977": {"campaignId":977,"customName":"Plus Retention - Domain","label":"Feature Activation","description":"Targets Plus customers who haven't connected or purchased a domain.","metrics":{"volume":"275","openRate":"43.6%","clickRate":"6.6%"}},
  "PEM978": {"campaignId":978,"customName":"Plus Retention - Email","label":"Feature Activation","description":"Targets Plus customers who haven't set up a business email.","metrics":{"volume":"1,390","openRate":"36.5%","clickRate":"3.9%"}},
  "PST979": {"campaignId":979,"customName":"Plus Retention - Stripe","label":"Feature Activation","description":"Targets Plus customers who haven't connected Stripe.","metrics":{"volume":"3,290","openRate":"39.1%","clickRate":"1.5%"}},
  "PPP980": {"campaignId":980,"customName":"Plus Retention - PayPal","label":"Feature Activation","description":"Targets Plus customers who haven't connected PayPal.","metrics":{"volume":"3,097","openRate":"38.0%","clickRate":"1.1%"}},
  "PGC981": {"campaignId":981,"customName":"Plus Retention - GMB Connection","label":"Feature Activation","description":"Targets Plus customers who haven't connected their Google Business Profile.","metrics":{"volume":"226","openRate":"36.6%","clickRate":"6.2%"}},
  "PGV982": {"campaignId":982,"customName":"Plus Retention - GMB Verification","label":"Feature Activation","description":"Targets Plus customers who haven't verified their Google Business Profile.","metrics":{"volume":"1,292","openRate":"42.6%","clickRate":"7.6%"}},
  "NPSF911": {"campaignId":911,"customName":"90-Day NPS Survey","label":"Survey","description":"Sends an NPS survey to customers who haven't been surveyed in the last 90 days. Measures satisfaction and flags at-risk accounts.","metrics":{"volume":"738","openRate":"51.2%","clickRate":"12.4%"}},
  "LRF854": {"campaignId":854,"customName":"Launch Retention Main Flow","label":"Main Flow","description":"Core retention sequence for Launch plan customers. Drives feature activation (domain, email, payments) to reduce churn.","metrics":{"volume":"11,857","openRate":"37.4%","clickRate":"1.8%"}},
  "LDO970": {"campaignId":970,"customName":"Launch Retention - Domain","label":"Feature Activation","description":"Targets Launch customers who haven't connected or purchased a domain yet.","metrics":{"volume":"193","openRate":"49.9%","clickRate":"7.0%"}},
  "LEI971": {"campaignId":971,"customName":"Launch Retention - Email","label":"Feature Activation","description":"Targets Launch customers who haven't set up a business email.","metrics":{"volume":"791","openRate":"40.1%","clickRate":"6.7%"}},
  "LST972": {"campaignId":972,"customName":"Launch Retention - Stripe","label":"Feature Activation","description":"Targets Launch customers who haven't connected Stripe for payments.","metrics":{"volume":"1,481","openRate":"37.2%","clickRate":"1.8%"}},
  "LPP973": {"campaignId":973,"customName":"Launch Retention - PayPal","label":"Feature Activation","description":"Targets Launch customers who haven't connected PayPal for payments.","metrics":{"volume":"1,415","openRate":"37.8%","clickRate":"1.9%"}},
  "PCL580": {"campaignId":580,"customName":"Launch Purchase atlas","label":"Payment Confirmation","description":"Confirms payment and sets expectations for new Launch plan customers. First touchpoint after purchase.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "PCP888": {"campaignId":888,"customName":"Plus Purchase atlas","label":"Payment Confirmation","description":"Confirms payment for Plus and Growth plan customers. Higher-tier onboarding kickoff.","metrics":{"volume":"3,805","openRate":"65.1%","clickRate":"12.9%"}},
  "TFC401": {"campaignId":401,"customName":"Smartform Chasers atlas","label":"SmartForm","description":"Primary sequence pushing new customers to complete the SmartForm so UENI can start building their site.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "DLC402": {"campaignId":402,"customName":"DLC Chasers atlas","label":"Booking","description":"Pushes customers who completed the SmartForm to book their Design & Launch Call.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "SFC879": {"campaignId":879,"customName":"SmartForm Re-engagement atlas","label":"SmartForm","description":"Re-engages customers who exhausted the primary SmartForm chaser flow without completing it.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "TFD403": {"campaignId":403,"customName":"Launch Post-SmartForm & DLC Booked atlas","label":"Handoff","description":"Confirms next steps after a customer has completed the SmartForm and booked their call. Bridges intake to build.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "TFD403_2": {"campaignId":403,"customName":"Plus Post-SmartForm & DLC Booked atlas","label":"Handoff","description":"Confirms next steps after a customer has completed the SmartForm and booked their call. Bridges intake to build.","metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"},"plan":"Launch"},
  "WBL287": {"campaignId":287,"customName":"Your website is live atlas","label":"Go-Live","description":"Notifies the customer that their website has been published and guides them through their new UENI dashboard.","metrics":{"volume":"7,325","openRate":"58.8%","clickRate":"14.7%"}},
  "MY": {"campaignId":887,"customName":"Mylo Partner Leads","label":"Partner","description":"Nurture sequence for leads referred by Mylo (business insurance partner). Educates on UENI's value and drives sign-up.","metrics":{"volume":"11,866","openRate":"14.4%","clickRate":"0.4%"}},
  "SW": {"campaignId":873,"customName":"Swyft Partner Leads","label":"Partner","description":"Nurture sequence for leads referred by Swyft (incorporation partner). Drives conversion from lead to paid customer.","metrics":{"volume":"4,956","openRate":"32.6%","clickRate":"0.9%"}},
  "WG": {"campaignId":988,"customName":"US Gov Business Database","label":"Cold Outreach","description":"Outreach to newly incorporated US businesses sourced from a public government database.","metrics":{"volume":"5,879","openRate":"48.5%","clickRate":"0.7%"}},
  "PS608": {"campaignId":608,"customName":"Pre-Signup Nurture","label":"Top of Funnel","description":"Email sequence for people who left their email on a landing page but haven't created an account yet.","metrics":{"volume":"2,014","openRate":"39.2%","clickRate":"4.1%"}},
  "PSL607": {"campaignId":607,"customName":"Post-Signup Nurture","label":"Pre-Purchase","description":"Email sequence for people who created an account but haven't completed payment. Core pre-purchase conversion flow.","metrics":{"volume":"21,075","openRate":"38.2%","clickRate":"3.9%"}},
  "EX572": {"campaignId":572,"metrics":{"volume":"147","openRate":"80.3%","clickRate":"66.7%"}},
  "EI": {"campaignId":651,"metrics":{"volume":"347","openRate":"43.2%","clickRate":"6.6%"}},
  "FB": {"campaignId":934,"metrics":{"volume":"268","openRate":"26.5%","clickRate":"0.0%"}},
  "GG": {"campaignId":932,"metrics":{"volume":"274","openRate":"7.7%","clickRate":"1.1%"}},
  "ADO926": {"campaignId":926},
  "REC": {"campaignId":1044},
  "CXD1039": {"campaignId":1039},
  "GPILOT994": {"campaignId":994},
  "SBA": {"campaignId":1035},
  "WX": {"campaignId":577},
  "PSNURTURE": {"campaignId":1050},
  "DLC2991": {"campaignId":991},
  "NPS906": {"campaignId":906},
  "CHKP775": {"campaignId":775},
  "REF481": {"campaignId":481},
  "UPS432": {"campaignId":432},
  "LCR1038": {"campaignId":1038},
  "WB21031": {"campaignId":1031},
  "UTP581": {"campaignId":581}
};
