export const initialCampaignMetadata: Record<string, any> = {
  "WBF964": {"campaignId":964,"customName":"Win-Back Lapsed Customers","label":"Win-Back","description":"Re-engagement flow for customers who have churned. Attempts to bring them back with targeted messaging.","metrics":{"volume":"248","openRate":"51.1%","clickRate":"0.0%"}},
  "LUF916": {"campaignId":916,"customName":"Launch → Upgrade Nudge","label":"Main Flow","description":"Long-running sequence nudging Launch plan customers to upgrade to Plus or Growth.","metrics":{"volume":"32,214","openRate":"34.5%","clickRate":"0.3%"}},
  "PLG1008": {"campaignId":1008,"customName":"Plus → Growth AM Emails","label":"Upgrade Pitch","description":"Targeted emails encouraging Plus customers to upgrade to the Growth plan.","metrics":{"volume":"132","openRate":"37.4%","clickRate":"3.3%"}},
  "UPGRADE918": {"campaignId":918,"customName":"Plus Upgrade Full Flow","label":"Main Flow","description":"Full nurture sequence encouraging Plus customers to upgrade, with multi-step touchpoints.","metrics":{"volume":"42,314","openRate":"36.0%","clickRate":"0.3%"}},
  "MTA250": {"campaignId":250,"customName":"Monthly → Annual Switch","label":"Billing Upsell","description":"Encourages monthly subscribers to switch to an annual billing plan. Focused on LTV extension.","metrics":{"volume":"4,169","openRate":"35.7%","clickRate":"0.7%"}},
  "PRF974": {"campaignId":974,"customName":"Plus Retention Main Flow","label":"Main Flow","description":"Core retention sequence for Plus plan customers. Drives full platform activation across all key features.","metrics":{"volume":"6,625","openRate":"37.9%","clickRate":"2.5%"}},
  "PDO977": {"campaignId":977,"customName":"Plus Retention - Domain","label":"Feature Activation","description":"Targets Plus customers who haven't connected or purchased a domain.","metrics":{"volume":"290","openRate":"39.6%","clickRate":"5.7%"}},
  "PEM978": {"campaignId":978,"customName":"Plus Retention - Email","label":"Feature Activation","description":"Targets Plus customers who haven't set up a business email.","metrics":{"volume":"2,184","openRate":"34.5%","clickRate":"3.1%"}},
  "PST979": {"campaignId":979,"customName":"Plus Retention - Stripe","label":"Feature Activation","description":"Targets Plus customers who haven't connected Stripe.","metrics":{"volume":"5,110","openRate":"39.0%","clickRate":"1.2%"}},
  "PPP980": {"campaignId":980,"customName":"Plus Retention - PayPal","label":"Feature Activation","description":"Targets Plus customers who haven't connected PayPal.","metrics":{"volume":"3,978","openRate":"36.9%","clickRate":"0.7%"}},
  "PGC981": {"campaignId":981,"customName":"Plus Retention - GMB Connection","label":"Feature Activation","description":"Targets Plus customers who haven't connected their Google Business Profile.","metrics":{"volume":"249","openRate":"35.1%","clickRate":"4.4%"}},
  "PGV982": {"campaignId":982,"customName":"Plus Retention - GMB Verification","label":"Feature Activation","description":"Targets Plus customers who haven't verified their Google Business Profile.","metrics":{"volume":"1,902","openRate":"40.8%","clickRate":"6.1%"}},
  "NPSF911": {"campaignId":911,"customName":"90-Day NPS Survey","label":"Survey","description":"Sends an NPS survey to customers who haven't been surveyed in the last 90 days. Measures satisfaction and flags at-risk accounts.","metrics":{"volume":"378","openRate":"44.4%","clickRate":"6.1%"}},
  "LRF854": {"campaignId":854,"customName":"Launch Retention Main Flow","label":"Main Flow","description":"Core retention sequence for Launch plan customers. Drives feature activation (domain, email, payments) to reduce churn.","metrics":{"volume":"7,395","openRate":"34.7%","clickRate":"2.1%"}},
  "LDO970": {"campaignId":970,"customName":"Launch Retention - Domain","label":"Feature Activation","description":"Targets Launch customers who haven't connected or purchased a domain yet.","metrics":{"volume":"115","openRate":"45.8%","clickRate":"7.5%"}},
  "LEI971": {"campaignId":971,"customName":"Launch Retention - Email","label":"Feature Activation","description":"Targets Launch customers who haven't set up a business email.","metrics":{"volume":"778","openRate":"32.1%","clickRate":"4.0%"}},
  "LST972": {"campaignId":972,"customName":"Launch Retention - Stripe","label":"Feature Activation","description":"Targets Launch customers who haven't connected Stripe for payments.","metrics":{"volume":"1,234","openRate":"34.9%","clickRate":"1.2%"}},
  "LPP973": {"campaignId":973,"customName":"Launch Retention - PayPal","label":"Feature Activation","description":"Targets Launch customers who haven't connected PayPal for payments.","metrics":{"volume":"971","openRate":"34.9%","clickRate":"1.7%"}},
  "PCL580": {"campaignId":580,"customName":"Launch Purchase atlas","label":"Payment Confirmation","description":"Confirms payment and sets expectations for new Launch plan customers. First touchpoint after purchase.","metrics":{"volume":"734","openRate":"53.1%","clickRate":"12.0%"}},
  "PCP888": {"campaignId":888,"customName":"Plus Purchase atlas","label":"Payment Confirmation","description":"Confirms payment for Plus and Growth plan customers. Higher-tier onboarding kickoff.","metrics":{"volume":"864","openRate":"59.6%","clickRate":"8.4%"}},
  "TFC401": {"campaignId":401,"customName":"Smartform Chasers atlas","label":"SmartForm","description":"Primary sequence pushing new customers to complete the SmartForm so UENI can start building their site.","metrics":{"volume":"1,107","openRate":"43.5%","clickRate":"11.7%"}},
  "DLC402": {"campaignId":402,"customName":"DLC Chasers atlas","label":"Booking","description":"Pushes customers who completed the SmartForm to book their Design & Launch Call.","metrics":{"volume":"121","openRate":"50.0%","clickRate":"30.2%"}},
  "SFC879": {"campaignId":879,"customName":"SmartForm Re-engagement atlas","label":"SmartForm","description":"Re-engages customers who exhausted the primary SmartForm chaser flow without completing it.","metrics":{"volume":"5,931","openRate":"33.8%","clickRate":"13.6%"}},
  "TFD403": {"campaignId":403,"customName":"Launch Post-SmartForm & DLC Booked atlas","label":"Handoff","description":"Confirms next steps after a customer has completed the SmartForm and booked their call. Bridges intake to build.","metrics":{"volume":"1,347","openRate":"66.7%","clickRate":"6.2%"}},
  "TFD403_2": {"campaignId":403,"customName":"Plus Post-SmartForm & DLC Booked atlas","label":"Handoff","description":"Confirms next steps after a customer has completed the SmartForm and booked their call. Bridges intake to build.","metrics":{"volume":"1,347","openRate":"66.7%","clickRate":"6.2%"},"plan":"Launch"},
  "WBL287": {"campaignId":287,"customName":"Your website is live atlas","label":"Go-Live","description":"Notifies the customer that their website has been published and guides them through their new UENI dashboard.","metrics":{"volume":"1,813","openRate":"52.9%","clickRate":"7.7%"}},
  "MY": {"campaignId":887,"customName":"Mylo Partner Leads","label":"Partner","description":"Nurture sequence for leads referred by Mylo (business insurance partner). Educates on UENI's value and drives sign-up.","metrics":{"volume":"10,451","openRate":"16.9%","clickRate":"0.6%"}},
  "SW": {"campaignId":873,"customName":"Swyft Partner Leads","label":"Partner","description":"Nurture sequence for leads referred by Swyft (incorporation partner). Drives conversion from lead to paid customer.","metrics":{"volume":"4,711","openRate":"37.9%","clickRate":"1.1%"}},
  "WG": {"campaignId":988,"customName":"US Gov Business Database","label":"Cold Outreach","description":"Outreach to newly incorporated US businesses sourced from a public government database.","metrics":{"volume":"5,693","openRate":"49.0%","clickRate":"0.7%"}},
  "PS608": {"campaignId":608,"customName":"Pre-Signup Nurture","label":"Top of Funnel","description":"Email sequence for people who left their email on a landing page but haven't created an account yet.","metrics":{"volume":"1,965","openRate":"39.8%","clickRate":"4.1%"}},
  "PSL607": {"campaignId":607,"customName":"Post-Signup Nurture","label":"Pre-Purchase","description":"Email sequence for people who created an account but haven't completed payment. Core pre-purchase conversion flow.","metrics":{"volume":"4,872","openRate":"31.5%","clickRate":"3.4%"}},
  "EX572": {"campaignId":572,"metrics":{"volume":"145","openRate":"81.8%","clickRate":"67.8%"}},
  "EI": {"campaignId":651,"metrics":{"volume":"334","openRate":"44.8%","clickRate":"7.0%"}},
  "FB": {"campaignId":934,"metrics":{"volume":"260","openRate":"29.1%","clickRate":"0.0%"}},
  "GG": {"campaignId":932,"metrics":{"volume":"262","openRate":"7.3%","clickRate":"1.1%"}},
  "ADO926": {"campaignId":926,"metrics":{"volume":"593","openRate":"38.8%","clickRate":"4.7%"}},
  "REC": {"campaignId":1044,"metrics":{"volume":"550,327","openRate":"49.0%","clickRate":"1.4%"}},
  "CXD1039": {"campaignId":1039,"metrics":{"volume":"523","openRate":"36.8%","clickRate":"5.3%"}},
  "GPILOT994": {"campaignId":994,"metrics":{"volume":"68","openRate":"57.1%","clickRate":"14.3%"}},
  "SBA": {"campaignId":1035,"metrics":{"volume":"1,213","openRate":"34.4%","clickRate":"3.1%"}},
  "WX": {"campaignId":577,"metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "PSNURTURE": {"campaignId":1050,"metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "DLC2991": {"campaignId":989,"metrics":{"volume":"34","openRate":"60.6%","clickRate":"3.0%"}},
  "NPS906": {"campaignId":906,"metrics":{"volume":"1,745","openRate":"40.0%","clickRate":"3.9%"}},
  "CHKP775": {"campaignId":775,"metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "REF481": {"campaignId":481,"metrics":{"volume":"144","openRate":"15.4%","clickRate":"7.7%"}},
  "UPS432": {"campaignId":432,"metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "LCR1038": {"campaignId":1038,"metrics":{"volume":"12","openRate":"63.6%","clickRate":"27.3%"}},
  "WB21031": {"campaignId":1031,"metrics":{"volume":"0","openRate":"0.0%","clickRate":"0.0%"}},
  "UTP581": {"campaignId":581,"metrics":{"volume":"1,672","openRate":"54.9%","clickRate":"3.1%"}}
};
