
export const campaignFlows: Record<string, any> = {
  "WG": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window 10:00–11:00' },
      { type: 'email', title: 'Video for your business', label: '', sublabel: '', campaignId: '1051', actionId: '53292' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: about our previous email', label: '', sublabel: '', campaignId: '1051', actionId: '53297' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Good news', label: '', sublabel: '', campaignId: '1051', actionId: '53299' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Questions about UENI?', label: '', sublabel: '', campaignId: '1051', actionId: '53301' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Did someone say new business website 🔥', label: '', sublabel: '', campaignId: '1051', actionId: '53303' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Can you help me?', label: '', sublabel: '', campaignId: '1051', actionId: '53305' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "MY": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window 9:30–10:30' },
      { type: 'email', title: 'About your business', label: '', sublabel: '', campaignId: '1052', actionId: '53354' },
      { type: 'delay', label: 'Time Delay', duration: '1 day + Send window 9:30–10:30' },
      { type: 'email', title: 'Re: your website & domain', label: '', sublabel: '', campaignId: '1052', actionId: '53326' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Last Hours ⏰ $550 off your website', label: '', sublabel: '', campaignId: '1052', actionId: '53343' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'You\'ve unlocked our best-ever offer', label: '', sublabel: '', campaignId: '1052', actionId: '53345' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Have Questions? We\'re Here to Help!', label: '', sublabel: '', campaignId: '1052', actionId: '53347' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: your website preview', label: '', sublabel: '', campaignId: '1052', actionId: '53349' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Don\'t skip this one', label: '', sublabel: '', campaignId: '1052', actionId: '53351' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'private sale -- $49 website', label: '', sublabel: '', campaignId: '1052', actionId: '53353' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Can you help me?', label: '', sublabel: '', campaignId: '1052', actionId: '53336' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "SW": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Your new business needs a website', label: '', sublabel: '', campaignId: '1053', actionId: '53378' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Re: your website & free domain name', label: '', sublabel: '', campaignId: '1053', actionId: '53380' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Last Hours ⏰ $550 off your website', label: '', sublabel: '', campaignId: '1053', actionId: '53382' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'You\'ve unlocked our best-ever offer', label: '', sublabel: '', campaignId: '1053', actionId: '53383' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Have Questions? We\'re Here to Help!', label: '', sublabel: '', campaignId: '1053', actionId: '53392' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: your website preview', label: '', sublabel: '', campaignId: '1053', actionId: '53393' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Don\'t skip this one', label: '', sublabel: '', campaignId: '1053', actionId: '53387' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'private sale -- $49 website', label: '', sublabel: '', campaignId: '1053', actionId: '53390' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Can you help me?', label: '', sublabel: '', campaignId: '1053', actionId: '53389' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "TFC401": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '2 hours' },
      { type: 'email', title: 'Your website build is waiting!', label: '', sublabel: '', campaignId: '1055', actionId: '53432' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Let\'s get your website live', label: '', sublabel: '', campaignId: '1055', actionId: '53433' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'SMS: Your team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1055', actionId: '53442' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Can I help?', label: '', sublabel: '', campaignId: '1055', actionId: '53434' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'We need your help here 👋', label: '', sublabel: '', campaignId: '1055', actionId: '53435' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Re: your website', label: '', sublabel: '', campaignId: '1055', actionId: '53436' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'SMS: Your team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1055', actionId: '53444' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Complete your onboarding form', label: '', sublabel: '', campaignId: '1055', actionId: '53437' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Action needed: complete this form', label: '', sublabel: '', campaignId: '1055', actionId: '53446' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "DLC402": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'email', title: "You're missing one key step", label: '', sublabel: '', campaignId: '1056', actionId: '53461' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'SMS: Your website needs your approval to go live', label: 'SMS', sublabel: '', campaignId: '1056', actionId: '53455' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'We need to speak to you', label: '', sublabel: '', campaignId: '1056', actionId: '53465' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Book your Launch Call', label: '', sublabel: '', campaignId: '1056', actionId: '53466' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "SFC879": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Tue 10:00–20:00' },
      { type: 'email', title: 'Let\'s get your website live', label: '', sublabel: '', campaignId: '1057', actionId: '53476' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'Our team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1057', actionId: '53481' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Can I help?', label: '', sublabel: '', campaignId: '1057', actionId: '53477' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'Our team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1057', actionId: '53482' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'We need your help here 👋', label: '', sublabel: '', campaignId: '1057', actionId: '53478' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'Our team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1057', actionId: '53483' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Re: your website', label: '', sublabel: '', campaignId: '1057', actionId: '53479' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'Our team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1057', actionId: '53484' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Can I help you?', label: '', sublabel: '', campaignId: '1057', actionId: '53480' },
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'sms', title: 'Our team is ready to build your website', label: 'SMS', sublabel: '', campaignId: '1057', actionId: '53485' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LRF854": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Ready to win online?', label: '', sublabel: '', campaignId: '854', actionId: '41510' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'branch', condition: 'Launch Retention - Domain' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Launch Retention - Email' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Launch Retention - Stripe' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Launch Retention - PayPal' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Quick recap ✅', label: '', sublabel: '', campaignId: '854', actionId: '49107' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Customers are searching for you ✅', label: '', sublabel: '', campaignId: '854', actionId: '49141' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Make your site yours', label: '', sublabel: '', campaignId: '854', actionId: '49143' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'New widgets for your website ✅', label: '', sublabel: '', campaignId: '854', actionId: '41531' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Let\'s build your email list ✅', label: '', sublabel: '', campaignId: '854', actionId: '41532' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Speak directly to your visitors ✅', label: '', sublabel: '', campaignId: '854', actionId: '41534' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Quick recap about Widgets ✅', label: '', sublabel: '', campaignId: '854', actionId: '41536' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Learn about your visitors ✅', label: '', sublabel: '', campaignId: '854', actionId: '41537' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: '3 tips to sell more services ✅', label: '', sublabel: '', campaignId: '854', actionId: '41547' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Set up your booking system ✅', label: '', sublabel: '', campaignId: '854', actionId: '41549' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Make your products shine ☀️', label: '', sublabel: '', campaignId: '854', actionId: '41550' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Set up your Shopping Cart 🛒', label: '', sublabel: '', campaignId: '854', actionId: '41552' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Do this today ✅', label: '', sublabel: '', campaignId: '854', actionId: '49148' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Want more customers from Google?', label: '', sublabel: '', campaignId: '854', actionId: '49149' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Need website updates?', label: '', sublabel: '', campaignId: '854', actionId: '49151' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Last chance — Plus sale ends today! ⏰', label: '', sublabel: '', campaignId: '854', actionId: '49153' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'What\'s a tracking pixel?', label: '', sublabel: '', campaignId: '854', actionId: '49155' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Quick SEO wins', label: '', sublabel: '', campaignId: '854', actionId: '49157' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Did you know?', label: '', sublabel: '', campaignId: '854', actionId: '49159' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: '6x more calls for your business', label: '', sublabel: '', campaignId: '854', actionId: '49161' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Last chance — $141 OFF ends tonight!', label: '', sublabel: '', campaignId: '854', actionId: '49163' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Your competitors\' secrets', label: '', sublabel: '', campaignId: '854', actionId: '49165' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Get more leads', label: '', sublabel: '', campaignId: '854', actionId: '49166' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Social proof 101', label: '', sublabel: '', campaignId: '854', actionId: '49169' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Write one blog this week', label: '', sublabel: '', campaignId: '854', actionId: '49171' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Essential steps for your UENI account ✅', label: '', sublabel: '', campaignId: '854', actionId: '49177' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'What\'s a lead magnet?', label: '', sublabel: '', campaignId: '854', actionId: '49179' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Remarketing made simple', label: '', sublabel: '', campaignId: '854', actionId: '49181' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'One question you need to answer', label: '', sublabel: '', campaignId: '854', actionId: '49183' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'email', title: 'Earn $100 per referral', label: '', sublabel: '', campaignId: '854', actionId: '49184' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Your opinion matters ✅', label: '', sublabel: '', campaignId: '854', actionId: '49253' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LDO970": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49109' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49112' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49603' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49606' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49609' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49612' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49639' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49642' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49645' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '970', actionId: '49648' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LEI971": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '49122' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '49124' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51270' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51272' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51276' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51278' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51300' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51302' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51306' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '971', actionId: '51308' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LST972": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '49135' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51320' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51323' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51326' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51329' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51332' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51335' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51338' },
      { type: 'delay', label: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51341' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '972', actionId: '51344' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LPP973": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '49139' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51354' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51357' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51360' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51363' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51366' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51369' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51372' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51375' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '973', actionId: '51378' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "TFD403": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'email', title: 'We are ready to build your website!', label: '', sublabel: '', campaignId: '1058', actionId: '53502' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'The resources you requested for your business', label: '', sublabel: '', campaignId: '1058', actionId: '53509' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Your team is at work!', label: '', sublabel: '', campaignId: '1058', actionId: '53506' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Website edits on-demand', label: '', sublabel: '', campaignId: '1058', actionId: '53507' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Opportunity for your business!', label: '', sublabel: '', campaignId: '1058', actionId: '53508' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "TFD403_2": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '1 hour' },
      { type: 'email', title: 'We are ready to build your website!', label: '', sublabel: '', campaignId: '1060', actionId: '53537' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'The resources you requested for your business', label: '', sublabel: '', campaignId: '1060', actionId: '53544' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Refer UENI = Get $100', label: '', sublabel: '', campaignId: '1060', actionId: '53538' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Your team is at work!', label: '', sublabel: '', campaignId: '1060', actionId: '53539' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Nearly there!', label: '', sublabel: '', campaignId: '1060', actionId: '53540' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "WBL287": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Your website is live 🎉', label: '', sublabel: '', campaignId: '1059', actionId: '53517' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'sms', title: 'Your UENI website is live', label: 'SMS', sublabel: '', campaignId: '1059', actionId: '53516' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "PCP888": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'UENI - Payment Confirmation', label: '', sublabel: '', campaignId: '1061', actionId: '53550' },
      { type: 'delay', label: 'Time Delay', duration: '1 minute' },
      { type: 'email', title: 'One step to start your website build', label: '', sublabel: '', campaignId: '1061', actionId: '53551' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "PCL580": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'UENI - Payment Confirmation', label: '', sublabel: '', campaignId: '1054', actionId: '53409' },
      { type: 'delay', label: 'Time Delay', duration: '1 minute' },
      { type: 'email', title: 'One step to start your website build', label: '', sublabel: '', campaignId: '1054', actionId: '53410' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "PS608": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '5 minutes' },
      { type: 'email', title: 'Welcome Email 1', label: 'pre-signup-us26-1', sublabel: 'Re: {{customer.venue_name | default: "your business"}}', campaignId: '1048', actionId: '53233' },
      { type: 'delay', label: 'Time Delay', duration: '2 hours' },
      { type: 'email', title: 'Support Call Offer', label: 'pre-signup-call-us26', sublabel: 'Questions? We\'re Here to Help!', campaignId: '1048', actionId: '53232' },
      { type: 'delay', label: 'Time Delay', duration: '16 hours' },
      { type: 'email', title: 'Follow-up', label: 'pre-signup-us26-2', sublabel: 'Re: follow-up', campaignId: '1048', actionId: '53231' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Website Preview', label: 'pre-signup-us26-3', sublabel: 'Your website is waiting for you', campaignId: '1048', actionId: '53230' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Preview Reminder', label: 'pre-signup-us26-4', sublabel: 'Re: your website preview', campaignId: '1048', actionId: '53229' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Quick Question', label: 'pre-signup-us26-5', sublabel: 'Quick question', campaignId: '1048', actionId: '53228' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: '5-Step Guide', label: 'pre-signup-us26-6', sublabel: 'From Zero to Website: 5-Step Guide', campaignId: '1048', actionId: '53227' },
      { type: 'timer', label: 'Time Window', sublabel: 'Wait until any day between 8:00 AM and 6:00 PM...' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Feedback Survey', label: 'presignup-US-survey', sublabel: 'Can you help me?', campaignId: '1048', actionId: '53225' },
      { type: 'exit', label: 'Exit' } ,
    ]
  },
  "PSNURTURE": {
    dynamic: true,
    campaignId: '1050'
  },
  "PSL607": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '5 minutes' },
      { type: 'email', title: 'Quick question', label: 'post-signup-us-1b', sublabel: 'Quick question', campaignId: '1050', actionId: '53257' },
      { type: 'delay', label: 'Time Delay', duration: '2 hours' },
      { type: 'email', title: 'Re: follow-up', label: 'post-signup-us-2b', sublabel: 'Re: follow-up', campaignId: '1050', actionId: '53259' },
      { type: 'delay', label: 'Time Delay', duration: '16 hours' },
      { type: 'email', title: '[1/5] From Zero to Website: 5-Step Guide', label: 'post-signup-us-3b', sublabel: '[1/5] From Zero to Website: 5-Step Guide', campaignId: '1050', actionId: '53260' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Quick challenge for you', label: 'post-signup-us-4b', sublabel: 'Quick challenge for you', campaignId: '1050', actionId: '53261' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: '[2/5] Local Visibility Checklist: Free Guide', label: 'post-signup-us-5b', sublabel: '[2/5] Local Visibility Checklist: Free Guide', campaignId: '1050', actionId: '53262' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Re: quick challenge', label: 'post-signup-us-6b', sublabel: 'Re: quick challenge', campaignId: '1050', actionId: '53263' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: '[3/5] Credibility Builder Kit: Free Guide', label: 'post-signup-us-7b', sublabel: '[3/5] Credibility Builder Kit: Free Guide', campaignId: '1050', actionId: '53271' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: '[4/5] Conversion Booster Cheatsheet: Free Guide', label: 'post-signup-us-8b', sublabel: '[4/5] Conversion Booster Cheatsheet: Free Guide', campaignId: '1050', actionId: '53273' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: '[5/5] Social Media in 20 Minutes a Week', label: 'post-signup-us-9b', sublabel: '[5/5] Social Media in 20 Minutes a Week', campaignId: '1050', actionId: '53274' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Re: The #1 Google Trick (5min read)', label: 'post-signup-us-10b', sublabel: 'Re: The #1 Google Trick (5min read)', campaignId: '1050', actionId: '53269' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Re: your website preview', label: 'post-signup-examplepagesa', sublabel: 'Re: your website preview', campaignId: '1050', actionId: '53280' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'One of the questions we hear the most...', label: 'post-signup-examplepages2a', sublabel: 'One of the questions we hear the most...', campaignId: '1050', actionId: '53281' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Can you help me?', label: 'postsignup-US-survey', sublabel: 'Can you help me?', campaignId: '1050', actionId: '53243' },
      { type: 'exit', label: 'Exit' } ,
    ]
  },
  "NPSF911": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: '25 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window' },
      { type: 'email', title: 'Quick 1-click feedback?', label: '', sublabel: '', campaignId: '906', actionId: '44890' },
      { type: 'delay', label: 'Time Delay', duration: '4 days' },
      { type: 'email', title: 'Re: Quick 1-click feedback?', label: '', sublabel: '', campaignId: '906', actionId: '44892' },
      { type: 'delay', label: 'Time Delay', duration: '4 days' },
      { type: 'email', title: '30 seconds feedback?', label: '', sublabel: '', campaignId: '906', actionId: '44894' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "LUF916": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: 'I want to help', label: '', sublabel: '', campaignId: '916', actionId: '45349' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: '1 new customer', label: '', sublabel: '', campaignId: '916', actionId: '45352' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'Widgets for your website', label: '', sublabel: '', campaignId: '916', actionId: '45376' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Mon 17:00–18:00' },
      { type: 'email', title: 'Customers are searching for you ✅', label: '', sublabel: '', campaignId: '916', actionId: '45378' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: 'Ready for the next chapter?', label: '', sublabel: '', campaignId: '916', actionId: '45354' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: 'Re: your business marketing', label: '', sublabel: '', campaignId: '916', actionId: '45355' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'What do you think?', label: '', sublabel: '', campaignId: '916', actionId: '45357' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Mon 17:00–18:00' },
      { type: 'email', title: 'Are your socials helping (or hurting)?', label: '', sublabel: '', campaignId: '916', actionId: '45380' },
      { type: 'delay', label: 'Time Delay', duration: 'Wed 17:00–18:00' },
      { type: 'email', title: 'When was the last time...', label: '', sublabel: '', campaignId: '916', actionId: '45384' },
      { type: 'delay', label: 'Time Delay', duration: 'Thu 9:15–10:15' },
      { type: 'email', title: '12 hours left...', label: '', sublabel: '', campaignId: '916', actionId: '45368' },
      { type: 'delay', label: 'Time Delay', duration: 'Thu 17:00–18:00' },
      { type: 'email', title: 'We\'ll do the work, you get the results', label: '', sublabel: '', campaignId: '916', actionId: '45385' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Wed 17:00–18:00' },
      { type: 'email', title: 'Growth for your business!', label: '', sublabel: '', campaignId: '916', actionId: '45360' },
      { type: 'delay', label: 'Time Delay', duration: 'Thu 9:15–10:15' },
      { type: 'email', title: '(open this before midnight)', label: '', sublabel: '', campaignId: '916', actionId: '45361' },
      { type: 'delay', label: 'Time Delay', duration: 'Thu 17:00–18:00' },
      { type: 'email', title: 'Quick question?', label: '', sublabel: '', campaignId: '916', actionId: '45362' },
      { type: 'delay', label: 'Time Delay', duration: 'Fri 9:30–10:30' },
      { type: 'email', title: 'You missed this?', label: '', sublabel: '', campaignId: '916', actionId: '45363' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "MTA250": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Mon–Fri 8:30–18:30' },
      { type: 'email', title: 'Save on your website plan', label: '', sublabel: '', campaignId: '250', actionId: '50582' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Re: Save on your UENI plan', label: '', sublabel: '', campaignId: '250', actionId: '50594' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "WBF964": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Every day 8:30–20:00' },
      { type: 'email', title: 'Your website is about to go offline', label: '', sublabel: '', campaignId: '964', actionId: '48895' },
      { type: 'exit', label: 'Exit' }
    ]
  },
  "PRF974": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Ready to win online?', label: '', sublabel: '', campaignId: '974', actionId: '49395' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'branch', condition: 'Plus Retention - Domain' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Plus Retention - Email' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Plus Retention - Stripe' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Plus Retention - PayPal' },
      { type: 'branch', condition: 'Plus Retention - GMB Connection' },
      { type: 'delay', label: 'Time Delay', duration: '3 days' },
      { type: 'branch', condition: 'Plus Retention - GMB Verification' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Quick recap ✅', label: '', sublabel: '', campaignId: '974', actionId: '49435' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Next essential steps ✅', label: '', sublabel: '', campaignId: '974', actionId: '49453' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: '3 tips to sell more services ✅', label: '', sublabel: '', campaignId: '974', actionId: '49411' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Set up your booking system ✅', label: '', sublabel: '', campaignId: '974', actionId: '49413' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Set up your Shopping Cart 🛒', label: '', sublabel: '', campaignId: '974', actionId: '49417' },
      { type: 'delay', label: 'Time Delay', duration: '1 day' },
      { type: 'email', title: 'Make your products shine ☀️', label: '', sublabel: '', campaignId: '974', actionId: '49419' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Earn $100 per referral', label: '', sublabel: '', campaignId: '974', actionId: '49421' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Let us do the work for you!', label: '', sublabel: '', campaignId: '974', actionId: '49424' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Your opinion matters ✅', label: '', sublabel: '', campaignId: '974', actionId: '49426' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Do you email your customers?', label: '', sublabel: '', campaignId: '974', actionId: '49427' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Get your products on Google ✅', label: '', sublabel: '', campaignId: '974', actionId: '49363' }
    ]
  },
  "PDO977": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49565' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49568' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49661' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49664' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49667' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49669' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49697' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49699' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49703' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Claim your custom domain!', label: '', sublabel: '', campaignId: '977', actionId: '49706' }
    ]
  },
  "PEM978": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49571' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49573' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49739' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49742' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49747' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49752' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49793' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49795' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49799' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Choose your professional email!', label: '', sublabel: '', campaignId: '978', actionId: '49801' }
    ]
  },
  "PST979": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49577' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49819' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49821' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49823' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49857' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Time to get paid!', label: '', sublabel: '', campaignId: '979', actionId: '49859' }
    ]
  },
  "PPP980": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49579' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49882' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49884' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49886' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49916' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect PayPal!', label: '', sublabel: '', campaignId: '980', actionId: '49918' }
    ]
  },
  "PGC981": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49581' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49930' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49932' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49934' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49964' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Connect your Google Business Profile', label: '', sublabel: '', campaignId: '981', actionId: '49966' }
    ]
  },
  "PGV982": {
    dynamic: false,
    steps: [
      { type: 'email', title: 'Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '49583' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '49980' },
      { type: 'delay', label: 'Time Delay', duration: '12 days' },
      { type: 'email', title: 'Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '49982' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '49984' },
      { type: 'delay', label: 'Time Delay', duration: '28 days' },
      { type: 'email', title: 'Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '50014' },
      { type: 'delay', label: 'Time Delay', duration: '2 days' },
      { type: 'email', title: 'Re: Let\'s verify your Google Business Profile', label: '', sublabel: '', campaignId: '982', actionId: '50016' }
    ]
  },
  "UPGRADE918": {
    dynamic: false,
    steps: [
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: 'Growth for your business!', label: '', sublabel: '', campaignId: '918', actionId: '45698' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: '(open this before midnight)', label: '', sublabel: '', campaignId: '918', actionId: '45699' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'What do you think?', label: '', sublabel: '', campaignId: '918', actionId: '45700' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Fri 9:30–10:30' },
      { type: 'email', title: 'You missed this?', label: '', sublabel: '', campaignId: '918', actionId: '45701' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: '1-on-1 marketing help for your business!', label: '', sublabel: '', campaignId: '918', actionId: '45619' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: 'Re: your business marketing', label: '', sublabel: '', campaignId: '918', actionId: '45620' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'Quick question?', label: '', sublabel: '', campaignId: '918', actionId: '45622' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Fri 9:30–10:30' },
      { type: 'email', title: 'Extension granted!', label: '', sublabel: '', campaignId: '918', actionId: '45624' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: 'Growth for your business!', label: '', sublabel: '', campaignId: '918', actionId: '45706' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: '(open this before midnight)', label: '', sublabel: '', campaignId: '918', actionId: '45707' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'What do you think?', label: '', sublabel: '', campaignId: '918', actionId: '45708' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Fri 9:30–10:30' },
      { type: 'email', title: 'You missed this?', label: '', sublabel: '', campaignId: '918', actionId: '45709' },
      { type: 'email', title: 'Re: 12 hours left', label: '', sublabel: '', campaignId: '918', actionId: '45659' },
      { type: 'delay', label: 'Time Delay', duration: '7 days' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Wed 17:00–18:00' },
      { type: 'email', title: '1-on-1 marketing help for your business!', label: '', sublabel: '', campaignId: '918', actionId: '45715' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 9:15–10:15' },
      { type: 'email', title: 'Re: your business marketing', label: '', sublabel: '', campaignId: '918', actionId: '45716' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Thu 17:00–18:00' },
      { type: 'email', title: 'Quick question?', label: '', sublabel: '', campaignId: '918', actionId: '45718' },
      { type: 'delay', label: 'Time Delay', duration: 'Send window: Fri 9:30–10:30' },
      { type: 'email', title: 'Extension granted!', label: '', sublabel: '', campaignId: '918', actionId: '45720' }
    ]
  }
};

